// @flow

export const GET_TRASH_REQUEST = 'GET_TRASH_REQUEST';
export const GET_TRASH_SUCCESS = 'GET_TRASH_SUCCESS';
export const GET_TRASH_FAILURE = 'GET_TRASH_FAILURE';

export const REMOVE_TRASH_REQUEST = 'REMOVE_TRASH_REQUEST';
export const REMOVE_TRASH_SUCCESS = 'REMOVE_TRASH_SUCCESS';
export const REMOVE_TRASH_FAILURE = 'REMOVE_TRASH_FAILURE';

export const ADD_TRASH_REQUEST = 'ADD_TRASH_REQUEST';
export const ADD_TRASH_SUCCESS = 'ADD_TRASH_SUCCESS';
export const ADD_TRASH_FAILURE = 'ADD_TRASH_FAILURE';